name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
    paths:
      - 'baifern-detection-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Grab your code from GitHub
      - uses: actions/checkout@v3

      # 2. Install the Hugging Face hub library
      - name: Install Hugging Face Hub
        run: pip install -U "huggingface_hub[cli]"

      # 3. Upload using the new 'hf' command
      - name: Direct API Upload to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          hf upload NoHaxJustTuL/baifern-detection-api ./baifern-detection-api . --repo-type space --exclude "*.pkl"